### PR TITLE
- Huge Update on Magma package

### PR DESCRIPTION
**Pull request by christianneurohr**
- Can be used now to make tests for period matrices
- Included small guide on how to use "readme"
- Abel-Jacobi not ready yet

### CODE REVIEW

**Comment by pascalmolin** [comment]
I feel more than uncomfortable with this pull request. You know I spend some (a lot of) time designing code and this magma package reflects much of the choices I made. When you copy some code, even from a collaborator, please credit the original author instead of putting your name on the header (this is also valid for other sources).

**Comment by christianneurohr** [comment]
Hello Pascal,
i'm very sorry for making you feel bad about this update. Let me assure you
that I have no intend of stealing your ideas, my only goal is to finish
this project. So, let's make things clear.

- I liked the implementation for superelliptic curves that I already had
(based of your pari code of course) and I think I put my share of own ideas
into this
 (like a different spanning tree, or intersections, homology, or a way to
compute differentials, Abel-Jacobi map, ... at least some things)
- I kept adjusting my code to how the paper developed, first of all to test
whether the theory works, and also because you told me that keeping the
code close to the theory is something we should aim for.
- Also I copied some of your choices to make the results comparable with
arb (spanning tree or intersections)
- I thought it was in your interest to have the best version of the
algorithm implemented (maybe that's only true for the arb version and not
for magma?), so I kept reading and understanding your code and ideas.
Most of the time I compared them to what I've already had and most of the
time I surrendered my own way to do things to yours, since I found it to be
superior
- Since your name is all in the arb-code and (sadly) I couldn't contribute
that much, I just wanted to have mine in the Magma code
so people can see that I did something

So, I'm not sure what you expect me to do, Should I put your name
everywhere instead of mine, or merely add yours to it? I can also go back
to an earlier version where things are not as optimal, but are not similar
to what you've done in arb.
Lastly, are you talking about any other authors in particular, or is that
just meant as general advice?

Sorry for this long Email, I don't want to do anything wrong here and this
situation makes me very sad..

Best,
Christian




2017-04-17 8:57 GMT+02:00 pascalmolin <notifications@github.com>:

**Comment by pascalmolin** [comment]
Christian,

I think you understand that when you borrow a way to write things that you
found superior there is some work behind and that it is not honest to wrap
this in Magma with your name. This is precisely what upsets me.

This is honesty, and well established practice: if you copy some code,
mention the original, a good implementation is much more work than a
theoretical algorithm. And if large portions are translated, write "adapted
from..." in the header (it also helps fixing both version if a bug is found
later, but this is not the main point). This was already true for my gp
code, for the symplectic reduction if you took it from sage...

Concerning our project, I consider that saying it is joint work already
acknowledges your contribution, which is real (experiments and checking
which made the final writing possible...). I wrote the arb code on top of
that, and I am not sure you realize the time it takes to write things the
way I write them. I put my name on that. I am happy that the magma version
benefits from this work and can be advertised as an implementation of this
article. So feel free to copy, but in this case acknowledge the origin of
parts which reflect my thinking. This is what the bsd licence asks people
to do (and of course your name has to be there also).

I hope this explains things clearly. I have lots of things to do right now
but I have corrections to make to the article, I hope I will manage before
the end of the week.

Pascal

2017-04-17 10:22 GMT+02:00 Christian Neurohr <notifications@github.com>:

**Comment by christianneurohr** [comment]
Thanks you very much for that clear and detailed response! It helped me to
see how wrong I was on this topic.

I meditated about this and realized that subconsciously I did this for very
stupid reasons. I will fix this as soon as possible.

Best,
Christian



2017-04-17 14:48 GMT+02:00 pascalmolin <notifications@github.com>:

**Pull request closed without merging**
